//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WEBBANGDIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangDia
    {
        public BangDia()
        {
            this.DatHangs = new HashSet<DatHang>();
        }
    
        public int MaBD { get; set; }
        public string TenBD { get; set; }
        public int MaLoai { get; set; }
        public int MaHSX { get; set; }
        public int MaDM { get; set; }
        public int MaCL { get; set; }
        [Display(Name = "Tiêu đề")]
        [Required(ErrorMessage = "Tiêu đề không được trống")]
        public string TieuDe { get; set; }
        [Display(Name = "Nội dung")]
        [Required(ErrorMessage = "Nội dung không được trống")]
        public string NoiDung { get; set; }
        public string AnhDaiDien { get; set; }
        [Display(Name = "Dung lượng")]
        [Required(ErrorMessage = "Dung lượng không được trống")]
        public string DungLuongTong { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Nhập 1 số")]
        public double Gia { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Nhập 1 số")]
        public double GiaKM { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Nhập 1 số")]
        public int SoLuongBoDia { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Nhập 1 số")]
        public int SoLuongHienCon { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<bool> An { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual ChatLuong ChatLuong { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual LoaiDia LoaiDia { get; set; }
        public virtual ICollection<DatHang> DatHangs { get; set; }
    }
}
