//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBBANGDIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public int MaLH { get; set; }
        public int MaTK { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }

        [Display(Name = "Yêu cầu")]
        [Required(ErrorMessage = "Yêu cầu không được trống")]
        public int MaYC { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<bool> An { get; set; }
        public Nullable<System.DateTime> NgayAn { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual YeuCau YeuCau { get; set; }
    }
}
