//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBBANGDIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiTaiKhoan
    {
        public LoaiTaiKhoan()
        {
            this.TaiKhoans = new HashSet<TaiKhoan>();
        }
    
        public int MaLoaiTK { get; set; }
        public string LoaiTK { get; set; }
    
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
    }
}
