//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBBANGDIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            this.DatHangs = new HashSet<DatHang>();
            this.LienHes = new HashSet<LienHe>();
        }
    
        public int MaTK { get; set; }
        public string TenTK { get; set; }
        public string HoTen { get; set; }
        public int NamSinh { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public int MaLoaiTK { get; set; }
        public Nullable<bool> An { get; set; }
        public Nullable<System.DateTime> NgayAn { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual ICollection<DatHang> DatHangs { get; set; }
        public virtual ICollection<LienHe> LienHes { get; set; }
        public virtual LoaiTaiKhoan LoaiTaiKhoan { get; set; }
    }
}
