//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBBANGDIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCau
    {
        public YeuCau()
        {
            this.LienHes = new HashSet<LienHe>();
        }
    
        public int MaYC { get; set; }
        public string TenYeuCau { get; set; }
    
        public virtual ICollection<LienHe> LienHes { get; set; }
    }
}
