//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBBANGDIA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebBangDiaEntities : DbContext
    {
        public WebBangDiaEntities()
            : base("name=WebBangDiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BangDia> BangDias { get; set; }
        public DbSet<ChatLuong> ChatLuongs { get; set; }
        public DbSet<DanhMuc> DanhMucs { get; set; }
        public DbSet<DatHang> DatHangs { get; set; }
        public DbSet<HangSanXuat> HangSanXuats { get; set; }
        public DbSet<LienHe> LienHes { get; set; }
        public DbSet<LoaiDia> LoaiDias { get; set; }
        public DbSet<LoaiHinhGiaoDich> LoaiHinhGiaoDiches { get; set; }
        public DbSet<LoaiTaiKhoan> LoaiTaiKhoans { get; set; }
        public DbSet<QuocGia> QuocGias { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TaiKhoan> TaiKhoans { get; set; }
        public DbSet<YeuCau> YeuCaus { get; set; }
    }
}
