//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBBANGDIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatHang
    {
        public int MaDH { get; set; }
        public int MaTK { get; set; }
        public int MaBD { get; set; }
        public int MaLoaiHinh { get; set; }
        public System.DateTime NgayDat { get; set; }
    
        public virtual BangDia BangDia { get; set; }
        public virtual LoaiHinhGiaoDich LoaiHinhGiaoDich { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
