//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBBANGDIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiDia
    {
        public LoaiDia()
        {
            this.BangDias = new HashSet<BangDia>();
        }
    
        public int MaLoai { get; set; }
        public string TenLoai { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<bool> An { get; set; }
    
        public virtual ICollection<BangDia> BangDias { get; set; }
    }
}
